package id.pajerosportdakar.carsale;
import javax.swing.*;
import java.awt.*;
import java.io.*;
import java.net.*;

public class CarDetailsFrame extends javax.swing.JFrame {
    private final Car car;
    
    public CarDetailsFrame(Car car, String username) {
        this.car = car;
        this.username = username;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbHeading = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbImage = new javax.swing.JLabel();
        ImageIcon imageIcon = new ImageIcon(car.getImagePath());
        Image image = imageIcon.getImage().getScaledInstance(310, 200, Image.SCALE_SMOOTH);
        lbImage.setIcon(new ImageIcon(image));
        jScrollPane1 = new javax.swing.JScrollPane();
        taDeskripsi = new javax.swing.JTextArea();
        lbDeskripsi = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbGetHarga = new javax.swing.JLabel();
        lbMerek = new javax.swing.JLabel();
        lbGetMerek = new javax.swing.JLabel();
        lbModel = new javax.swing.JLabel();
        lbGetModel = new javax.swing.JLabel();
        lbTahun = new javax.swing.JLabel();
        lbGetTahun = new javax.swing.JLabel();
        lbGetOdo = new javax.swing.JLabel();
        lbOdometer = new javax.swing.JLabel();
        lbJenisBBM = new javax.swing.JLabel();
        lbGetBBM = new javax.swing.JLabel();
        lbGetLokasi = new javax.swing.JLabel();
        lbTransmisi = new javax.swing.JLabel();
        lbGetGearbox = new javax.swing.JLabel();
        lbWarna = new javax.swing.JLabel();
        lbGetWarna = new javax.swing.JLabel();
        lbNamaPenjual = new javax.swing.JLabel();
        lbGetPenjual = new javax.swing.JLabel();
        lbKubikasi = new javax.swing.JLabel();
        lbGetKubikasi = new javax.swing.JLabel();
        tbKembali = new javax.swing.JButton();
        tbBeli = new javax.swing.JButton();
        tbHapusMobil = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Informasi Kendaraan");

        lbHeading.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbHeading.setText("Info Kendaraan");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbImage, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
        );

        taDeskripsi.setEditable(false);
        taDeskripsi.setColumns(20);
        taDeskripsi.setRows(5);
        taDeskripsi.setText(car.getDeskripsi());
        jScrollPane1.setViewportView(taDeskripsi);

        lbDeskripsi.setText("Deskripsi:");

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbGetHarga.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbGetHarga.setText("Rp" + car.getHarga());

        lbMerek.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbMerek.setText("Merek");

        lbGetMerek.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbGetMerek.setText(car.getMerek());

        lbModel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbModel.setText("Model");

        lbGetModel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbGetModel.setText(car.getModel());

        lbTahun.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbTahun.setText("Tahun");

        lbGetTahun.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbGetTahun.setText(car.getTahun());

        lbGetOdo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbGetOdo.setText(car.getOdometer());

        lbOdometer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbOdometer.setText("Odometer");

        lbJenisBBM.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbJenisBBM.setText("Jenis BBM");

        lbGetBBM.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbGetBBM.setText(car.getJenisBBM());

        lbGetLokasi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbGetLokasi.setText("Lokasi: "  + car.getLokasi());

        lbTransmisi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbTransmisi.setText("Transmisi");

        lbGetGearbox.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbGetGearbox.setText(car.getJenisGearbox());

        lbWarna.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbWarna.setText("Warna");

        lbGetWarna.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbGetWarna.setText(car.getWarna());

        lbNamaPenjual.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbNamaPenjual.setText("Dijual oleh");

        lbGetPenjual.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbGetPenjual.setText(car.getNamaPenjual());

        lbKubikasi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbKubikasi.setText("Kubikasi");

        lbGetKubikasi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbGetKubikasi.setText(car.getKubikasi() + " cc");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbGetHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbGetLokasi, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNamaPenjual, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbGetPenjual)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbModel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbMerek, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lbGetTahun, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbTahun, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lbWarna, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbJenisBBM, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbGetBBM, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbGetWarna))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbTransmisi, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbKubikasi, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbOdometer, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbGetOdo, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(lbGetGearbox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbGetKubikasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lbGetMerek, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                        .addComponent(lbGetModel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbGetHarga)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbGetLokasi)
                .addGap(9, 9, 9)
                .addComponent(lbMerek, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbGetMerek)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbModel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbGetModel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbTahun)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbGetTahun))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbOdometer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbGetOdo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbJenisBBM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbGetBBM))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbTransmisi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbGetGearbox)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbWarna)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbGetWarna))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbKubikasi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbGetKubikasi)))
                .addGap(18, 18, 18)
                .addComponent(lbNamaPenjual)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbGetPenjual)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lbDeskripsi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbDeskripsi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );

        tbKembali.setText("Kembali");
        tbKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbKembaliActionPerformed(evt);
            }
        });

        tbBeli.setText("Beli Mobil Ini");
        tbBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbBeliActionPerformed(evt);
            }
        });

        tbHapusMobil.setText("Hapus Mobil");
        tbHapusMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbHapusMobilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tbKembali)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tbHapusMobil)
                        .addGap(18, 18, 18)
                        .addComponent(tbBeli))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lbHeading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbKembali)
                    .addComponent(tbBeli)
                    .addComponent(tbHapusMobil))
                .addGap(17, 17, 17))
        );

        if (username.equals(car.getNamaPenjual())) {
            tbHapusMobil.setVisible(true);
        } else {
            tbHapusMobil.setVisible(false);
        }

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbKembaliActionPerformed
        // TODO add your handling code here:
        new MainFrame(username, Main.carList).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tbKembaliActionPerformed

    private void tbBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbBeliActionPerformed
        // TODO add your handling code here:
        if (car.getNamaPenjual().equals(username)) {
            JOptionPane.showMessageDialog(this, "Kamu tidak bisa membeli mobil yang kamu jual!", "Beli Mobil", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        Object[] options = {"Hubungi", "Batal"}; // array utk custom button text
        int a = JOptionPane.showOptionDialog(this, """
                Untuk membeli mobil ini, kamu bisa menghubungi penjual.
                Nomor Penjual: +62""" + car.getNomorPenjual() + "\nKamu akan dialihkan ke halaman web baru (WhatsApp)", 
                "Beli Mobil", 
                JOptionPane.YES_NO_OPTION, 
                JOptionPane.QUESTION_MESSAGE, 
                null, 
                options, // custom option button text
                options[0]); // atur pilihan default ke 0 (pilihan ya/hubungi)
        
        if (a == 0) { // jika pengguna memilih hubungi
            openWebPage("https://wa.me/62" + car.getNomorPenjual()); // buka wa sesuai nomor penjual (misal: wa.me/62 + 811xxx)
        }
    }//GEN-LAST:event_tbBeliActionPerformed

    private void tbHapusMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbHapusMobilActionPerformed
        // TODO add your handling code here:
        int index = Main.carList.indexOf(car);
        String namaPenjual = car.getNamaPenjual();
        String currentUser = username;
        
        Object[] options = {"Hapus", "Tidak"};
        String msg = "<html>" +
                     "<p>Apakah kamu yakin ingin menghapus mobil ini dari daftar?</p>" +
                     "<p><b>PERINGATAN:</b> Tindakan ini <b><u>bersifat permanen dan tidak dapat diurungkan!</b></u></p>" +
                     "</html>";
        
        int pilihan = JOptionPane.showOptionDialog(this, 
                msg,
                "Konfirmasi Penghapusan Mobil",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE,
                null,
                options,
                options[1]);
        
        if (pilihan == 0) {
            if (index != -1) {
                if (namaPenjual.equals(currentUser)) {
                    Main.carList.remove(index);
                    Main.saveCarData();
                    JOptionPane.showMessageDialog(this, "Mobil berhasil dihapus.", "Info", JOptionPane.INFORMATION_MESSAGE);
                    new MainFrame(username, Main.carList).setVisible(true);
                    this.dispose();
                } else {  
                    JOptionPane.showMessageDialog(this, "Tidak bisa menghapus mobil. \nIni bukan mobilmu le, jangan lah memutus rejeki orang", "Galat", JOptionPane.ERROR_MESSAGE);  
                }  
            }
        }
    }//GEN-LAST:event_tbHapusMobilActionPerformed
    
    private void openWebPage(String urlString) {  
        try { 
            URI uri = new URI(urlString);  
            Desktop.getDesktop().browse(uri); // buka url di browser 
        } catch (IOException | URISyntaxException e) {  
            JOptionPane.showMessageDialog(this, "Tidak dapat membuka halaman web.\nAlasan: " + e.getMessage(), "Galat", JOptionPane.ERROR_MESSAGE);  
        }  
    }  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbDeskripsi;
    private javax.swing.JLabel lbGetBBM;
    private javax.swing.JLabel lbGetGearbox;
    private javax.swing.JLabel lbGetHarga;
    private javax.swing.JLabel lbGetKubikasi;
    private javax.swing.JLabel lbGetLokasi;
    private javax.swing.JLabel lbGetMerek;
    private javax.swing.JLabel lbGetModel;
    private javax.swing.JLabel lbGetOdo;
    private javax.swing.JLabel lbGetPenjual;
    private javax.swing.JLabel lbGetTahun;
    private javax.swing.JLabel lbGetWarna;
    private javax.swing.JLabel lbHeading;
    private javax.swing.JLabel lbImage;
    private javax.swing.JLabel lbJenisBBM;
    private javax.swing.JLabel lbKubikasi;
    private javax.swing.JLabel lbMerek;
    private javax.swing.JLabel lbModel;
    private javax.swing.JLabel lbNamaPenjual;
    private javax.swing.JLabel lbOdometer;
    private javax.swing.JLabel lbTahun;
    private javax.swing.JLabel lbTransmisi;
    private javax.swing.JLabel lbWarna;
    private javax.swing.JTextArea taDeskripsi;
    private javax.swing.JButton tbBeli;
    private javax.swing.JButton tbHapusMobil;
    private javax.swing.JButton tbKembali;
    // End of variables declaration//GEN-END:variables
    private final String username;
}
