package id.pajerosportdakar.carsale;
import java.util.ArrayList;
import javax.swing.*;
import java.awt.*;

public class MainFrame extends javax.swing.JFrame {
    
    public MainFrame(String username, ArrayList<Car> carList) {
        this.username = username;
        this.carList = carList;
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbWelcome = new javax.swing.JLabel();
        tbTambahMobil = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listModel = new javax.swing.DefaultListModel<>();
        carJList = new javax.swing.JList<>(listModel);
        for (Car car : carList) {
            listModel.addElement(car.getMerek() + " " + car.getModel()); // Menambah nama mobil ke model
        }
        ;
        panelInfo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lbImage = new javax.swing.JLabel();
        lbHarga = new javax.swing.JLabel();
        lbNama = new javax.swing.JLabel();
        tbDetail = new javax.swing.JButton();
        tbKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Utama");
        setMinimumSize(new java.awt.Dimension(600, 400));

        lbWelcome.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbWelcome.setText(" Selamat datang, " + username + "!");

        tbTambahMobil.setText("Tambah Mobil Baru...");
        tbTambahMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbTambahMobilActionPerformed(evt);
            }
        });

        carJList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                carJListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(carJList);

        panelInfo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbImage, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
        );

        lbHarga.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbHarga.setText("");

        lbNama.setText("");

        tbDetail.setText("Detail");
        tbDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbDetailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelInfoLayout = new javax.swing.GroupLayout(panelInfo);
        panelInfo.setLayout(panelInfoLayout);
        panelInfoLayout.setHorizontalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbHarga, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbNama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInfoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(tbDetail)))
                .addContainerGap())
        );
        panelInfoLayout.setVerticalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbHarga)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbNama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addComponent(tbDetail)
                .addContainerGap())
        );

        tbKeluar.setText("Logout");
        tbKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbWelcome)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tbTambahMobil, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tbKeluar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbWelcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbTambahMobil)
                    .addComponent(tbKeluar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbTambahMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbTambahMobilActionPerformed
        new AddCarFrame(Main.carList, username).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tbTambahMobilActionPerformed

    private void tbKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbKeluarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new LoginFrame(Main.userList).setVisible(true); 
    }//GEN-LAST:event_tbKeluarActionPerformed

    private void tbDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbDetailActionPerformed
        // TODO add your handling code here:
        int index = carJList.getSelectedIndex(); // mendapatkan indeks yang dipilih  
        if (index != -1) {  
            Car selectedCar = carList.get(index); // ambil mobil yang dipilih  
            new CarDetailsFrame(selectedCar).setVisible(true); // buka tampilan detail mobil 
        } else {  
            JOptionPane.showMessageDialog(this, "Silakan pilih mobil terlebih dahulu.", "Info", JOptionPane.INFORMATION_MESSAGE);  
        }  
    }//GEN-LAST:event_tbDetailActionPerformed

    private void carJListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_carJListValueChanged
        // TODO add your handling code here:
        if (!evt.getValueIsAdjusting()) { // memastikan pilihan tidak berubah
            int index = carJList.getSelectedIndex(); // mendapatkan indeks yang dipilih  
            if (index != -1) {  
                Car selectedCar = carList.get(index); // ambil mobil yang dipilih  
                displayCarDetails(selectedCar); // tampilkan informasi detail mobil  
            }  
        }   
    }//GEN-LAST:event_carJListValueChanged

    private void displayCarDetails(Car car) {  
        // menampilkan gambar  
        ImageIcon imageIcon = new ImageIcon(car.getImagePath());  
        Image image = imageIcon.getImage().getScaledInstance(320, 200, Image.SCALE_SMOOTH); // mengubah ukuran gambar  
        lbImage.setIcon(new ImageIcon(image)); // menampilkan gambar mobil  

        // menampilkan harga, merek dan model  
        lbHarga.setText("Rp" + car.getHarga());  
        lbNama.setText(car.getMerek() + " " + car.getModel());  
    }  
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> carJList;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbHarga;
    private javax.swing.JLabel lbImage;
    private javax.swing.JLabel lbNama;
    private javax.swing.JLabel lbWelcome;
    private javax.swing.JPanel panelInfo;
    private javax.swing.JButton tbDetail;
    private javax.swing.JButton tbKeluar;
    private javax.swing.JButton tbTambahMobil;
    // End of variables declaration//GEN-END:variables
    private final String username;
    private final ArrayList<Car> carList;
    private DefaultListModel<String> listModel;
}

