package id.pajerosportdakar.carsale;
import javax.swing.*;
import java.util.ArrayList;

public class RegistrationFrame extends JFrame {
    
    public RegistrationFrame(ArrayList<User> userList) {
        this.userList = userList;
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbHeader = new javax.swing.JLabel();
        lbUsername = new javax.swing.JLabel();
        tfUsername = new javax.swing.JTextField();
        lbNomorTel = new javax.swing.JLabel();
        tfNomorTel = new javax.swing.JTextField();
        lbKodeTel = new javax.swing.JLabel();
        pfPass = new javax.swing.JPasswordField();
        tbRegister = new javax.swing.JButton();
        lbPass = new javax.swing.JLabel();
        tbLogin = new javax.swing.JButton();
        chbShowPass = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        pfConfirmPass = new javax.swing.JPasswordField();
        lbConfirmPass = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registrasi");

        lbHeader.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lbHeader.setText(" Registrasi Pengguna");

        lbUsername.setText("Nama Pengguna");

        lbNomorTel.setText("Nomor Telepon");

        lbKodeTel.setText("+62");

        tbRegister.setText("Daftar!");
        tbRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbRegisterActionPerformed(evt);
            }
        });

        lbPass.setText("Buat Kata Sandi");

        tbLogin.setText("Login aja dehh...");
        tbLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbLoginActionPerformed(evt);
            }
        });

        chbShowPass.setText("Tampilkan Sandi");
        chbShowPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbShowPassActionPerformed(evt);
            }
        });

        jLabel1.setText("Format: 8xxxxxx (max 15 digit)");

        lbConfirmPass.setText("Konfirmasi Kata Sandi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 437, Short.MAX_VALUE)
                .addComponent(tbLogin)
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbNomorTel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lbKodeTel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfNomorTel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbRegister)
                            .addComponent(jLabel1))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chbShowPass)
                            .addComponent(pfPass, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbPass)
                            .addComponent(pfConfirmPass, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbConfirmPass))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addComponent(lbHeader)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbUsername)
                    .addComponent(lbPass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pfPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbNomorTel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfNomorTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbKodeTel)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbConfirmPass, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pfConfirmPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(chbShowPass))
                .addGap(26, 26, 26)
                .addComponent(tbRegister)
                .addGap(59, 59, 59)
                .addComponent(tbLogin)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbRegisterActionPerformed
        // TODO add your handling code here:
        registerUser();
    }//GEN-LAST:event_tbRegisterActionPerformed

    private void tbLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbLoginActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(this, "Apakah kamu yakin ingin batal pendaftaran?\nData yang kamu masukkan bakal ilang!", "Registrasi", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (a == JOptionPane.YES_OPTION) {
            new LoginFrame(userList).setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_tbLoginActionPerformed

    private void chbShowPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbShowPassActionPerformed
        // TODO add your handling code here:
        if (chbShowPass.isSelected()) {
            pfPass.setEchoChar('\u0000');
            pfConfirmPass.setEchoChar('\u0000'); // menampilkan password
        } else {
            pfPass.setEchoChar((Character) UIManager.get("PasswordField.echoChar")); // atur pf menjadi ....
            pfConfirmPass.setEchoChar((Character) UIManager.get("PasswordField.echoChar"));
        }
    }//GEN-LAST:event_chbShowPassActionPerformed
    
    private void registerUser() {  
        String username = tfUsername.getText();  
        String password = new String(pfPass.getPassword());  
        String confirmPassword = new String(pfConfirmPass.getPassword());  
        String phone = tfNomorTel.getText();  
        
        if (username.isEmpty() || password.isEmpty() || confirmPassword.isEmpty() || phone.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Registrasi Gagal. \nData kosong atau tidak sah. Mohon periksa kembali data yang anda masukkan.", "Galat", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (!password.equals(confirmPassword)) {  
            JOptionPane.showMessageDialog(this, "Registrasi Gagal! \nKata sandi tidak cocok.", "Galat", JOptionPane.ERROR_MESSAGE);  
            return;  
        } 
        
        if (!User.validatePwd(password)) {  
            JOptionPane.showMessageDialog(this, """
                                                Registrasi Gagal! 
                                                Kata sandi harus terdiri dari 8-20 karakter, mengandung masing-masing 
                                                setidaknya satu huruf kecil, huruf besar, angka, dan simbol.""",
                                                "Galat",
                                                JOptionPane.ERROR_MESSAGE);  
            return;  
        }  

        if (!User.validateNomor(phone)) {
            JOptionPane.showMessageDialog(this, """
                                                Registrasi Gagal! 
                                                Nomor telepon harus berupa angka, terdiri dari setidaknya 6-15 digit, dan berawalan '8'.""", 
                                                "Galat", 
                                                JOptionPane.ERROR_MESSAGE);
            return;
        } 
        
        userList.add(new User(username, password, phone));  
        Main.saveData();
        JOptionPane.showMessageDialog(this, "Registrasi Sukses", "Registrasi", JOptionPane.INFORMATION_MESSAGE);  
        new LoginFrame(userList).setVisible(true);
        this.dispose();
    }  
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chbShowPass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbConfirmPass;
    private javax.swing.JLabel lbHeader;
    private javax.swing.JLabel lbKodeTel;
    private javax.swing.JLabel lbNomorTel;
    private javax.swing.JLabel lbPass;
    private javax.swing.JLabel lbUsername;
    private javax.swing.JPasswordField pfConfirmPass;
    private javax.swing.JPasswordField pfPass;
    private javax.swing.JButton tbLogin;
    private javax.swing.JButton tbRegister;
    private javax.swing.JTextField tfNomorTel;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
    private final ArrayList<User> userList;
}    
